## Before attempting to run please provide the user and password login details for the ADES endpoint
# logindetails=user:password 

@scheme = https
@ades = test.eodatahub.org.uk/ades
@username= eric
@workspace = test-workspace
@accessPoint = arn:aws:s3:eu-west-2:312280911266:accesspoint/test-access-point
@fileName = s3/file/key
@logindetails = username:password

@deployStatus = {{deployProcessJson.response.headers.Location}}
@executeStatus = {{executeProcess.response.headers.Location}}

###

# @name deleteProcess
DELETE {{scheme}}://{{ades}}/{{username}}/ogc-api/processes/download-file HTTP/1.1
Authorization: Basic {{logindetails}}
Accept: application/json

###


# @name listProcesses
GET {{scheme}}://{{ades}}/{{username}}/ogc-api/processes HTTP/1.1
Authorization: Basic {{logindetails}}
Accept: application/json

###

# @name deployProcessJson
POST {{scheme}}://{{ades}}/{{username}}/ogc-api/processes HTTP/1.1
Authorization: Basic {{logindetails}}
Accept: application/json
Content-Type: application/cwl+yaml

< download-file.cwl

###

# @name getDeployStatus
GET {{deployStatus}} HTTP/1.1
Authorization: Basic {{logindetails}}
Accept: application/json

###

# @name getProcessDetails
GET {{scheme}}://{{ades}}/{{username}}/ogc-api/processes/download-file HTTP/1.1
Authorization: Basic {{logindetails}}
Accept: application/json

###

# @name executeProcess
POST {{scheme}}://{{ades}}/{{username}}/ogc-api/processes/download-file/execution HTTP/1.1
Authorization: Basic {{logindetails}}
Accept: application/json
Content-Type: application/json
Prefer: respond-async

{
  "inputs": {
    "workspace": "{{workspace}}",
      "access_point": "{{accessPoint}}",
      "file_name":  "{{fileName}}",
  }
}

###

# @name getExecuteStatus
GET {{executeStatus}} HTTP/1.1
Authorization: Basic {{logindetails}}
Accept: application/json

###

# @name getProcessingResults
GET {{executeStatus}}/results HTTP/1.1
Authorization: Basic {{logindetails}}
Accept: application/json

###

# @name undeployProcess
DELETE {{scheme}}://{{ades}}/{{username}}/ogc-api/processes/download-file HTTP/1.1
Authorization: Basic {{logindetails}}
Accept: application/json

###

# @name listJobs
GET {{scheme}}://{{ades}}/{{username}}/ogc-api/jobs HTTP/1.1
Authorization: Basic {{logindetails}}
Accept: application/json

###